### ISSUE TITLE
CYTTSP4 and CYTTSP5

### ISSUE THREAD

**Issue by teodimoff** [bartcubbins/kernel_kanuti_mainline#1] opened 2020-09-14 18:56 UTC
Cool project. I was able to make my sony m4 to work and boot, but the touchscreen does not work, and its getting hotter while it works so i guess i did not tune some thermal sensor in dts corectly. I am relatevly new to kernel dev and dts layout. I tried to port the  CYTTSP4 CYTTSP5 from the sony repo but its backward incompatible. Do you plan to add it. Any pointers on how can i help? Also i need to find proper wifi firmware and would apreciate any help. Thanks.

**Comment by teodimoff** [comment] 2020-09-14 19:02
Well i shoud have looked the commits from yesterday. I will try with the inital port of CYTTSP4. Dont know if it is on cyttps4 or cyttps5.

**Comment by bartcubbins** [comment] 2020-09-15 05:09
I'm glad to hear that someone else is interested in this device😊

1. About the touchscreen, please try to rebuild the kernel after the last changes. I added hardware detection logic that can determine and show in the kernel log which version of the CYTTSP is installed on the device. If it turns out that you really have CYTTSP5 installed, I will add support for it.
2. Regarding the temperature of the device, MSM8939 SoC itself is very hot, so even at such an early stage of development, the CPU frequencies scaling does not work quite correctly.
3. Regarding the WCNSS firmware, as soon as possible I will publish device three for the Android 11, which also will contain all the firmware used by the device. But you can find it yourself on your own device. You just need to mount the modem partition (/dev/mmcblk0p18)

P.S. The kernel is not very stable yet and it's very common to get a race condition during probing or kernel panic..

Best regards,
Pavel

**Comment by bartcubbins** [comment] 2020-09-15 05:15
I'm glad to hear that someone else is interested in this device😊

1. About the touchscreen, please try to rebuild the kernel after the last changes. I added hardware detection logic that can determine and show in the kernel log which version of the CYTTSP is installed on the device. If it turns out that you really have CYTTSP5 installed, I will add support for it.
2. Regarding the temperature of the device, MSM8939 SoC itself is very hot, so even at such an early stage of development, the CPU frequencies scaling does not work quite correctly.
3. Regarding the WCNSS firmware, as soon as possible I will publish device three for the Android 11, which also will contain all the firmware used by the device. But you can find it yourself on your own device. You just need to mount the modem partition (/dev/mmcblk0p18)

P.S. The kernel is not very stable yet and it's very common to get a race condition or kernel panic during probing..

Best regards,
Pavel

**Comment by teodimoff** [comment] 2020-09-15 08:36
Yes, yes with the recent commit, the touch screen works. Thanks. Yes there are few kernel panics sometimes but it will get stable. I will see if i can get wifi working today.  The sound is not working yet. I will try to backport the dts from xperia (if its even that the case that i has to be done from the dts.). Other than that is pretty cool to run on mainline actually. If i have made some progress i will repot. Thank you for putting effort in to this.

**Comment by teodimoff** [comment] 2020-09-15 13:42
Ok now the wifi works. I had mounted and downloaded the files from mmcblk0p18. Thank you for that. What are the modem firmware files? For the gsm network or something else? I will try to port msm8939-audio-external_codec.dtsi and msm8939-audio-internal_codec.dtsi tonight for the audio. Any other interesting presents from the  other devices mmcblk0pXX ? :)  Thare are some issues in wcXX around clk.

**Comment by bartcubbins** [comment] 2020-09-15 15:07
I already have an audio implementation in one of my local branches. I will push the changes after refactoring. Don't waste your time;)
Modem firmware is needed for its operation, as well as Adreno, WCNSS, etc.
About the partitions, I think you will not find anything else interesting. But here's partition map, just in case
```
P00: GPT (00000000, 00000100)
P01: TA (00000100, 00001000)
P02: sbl1 (00001100, 00000400)
P03: s1sbl (00001500, 00000200)
P04: aboot (00001700, 00000800)
P05: rpm (00001F00, 00000400)
P06: tz (00002300, 00000400)
P07: hyp (00002700, 00000400)
P08: alt_sbl1 (00002B00, 00000400)
P09: alt_s1sbl (00002F00, 00000200)
P10: alt_aboot (00003100, 00000800)
P11: alt_rpm (00003900, 00000400)
P12: alt_tz (00003D00, 00000400)
P13: alt_hyp (00004100, 00000400)
P14: fsg (00006000, 00000C00)
P15: modemst1 (00008000, 00000C00)
P16: modemst2 (0000A000, 00000C00)
P17: persist (0000C000, 00010000)
P18: modem (0001C000, 00020000)
P19: boot (0003C000, 00014000)
P20: rdimage (00050000, 00010000)
P21: FOTAKernel (00060000, 00014000)
P22: ssd (00074000, 00000010)
P23: DDR (00074010, 00000040)
P24: config (00074050, 00000400)
P25: LTALabel (00074450, 00008000)
P26: apps_log (0007E000, 00004000)
P27: oem (00082000, 0007C000)
P28: cache (000FE000, 00064000)
P29: userdata (00162000, 00832000)
P30: system (00994000, 004FBE00)
```

**Comment by teodimoff** [comment] 2020-09-15 15:10
Oh cool... i will wait then. The modem sound essential but its not refferenced in CONFIG_EXTRA_FIRMWARE, so there is maybe some other way that refference the firmware i dont know. Either way, Thank you! One more thing left, when i plug in usb (or usb in dc for charging only) the phone does not go in charge mode, but this might not be kernel related but somewhere upsream (for postmarketos charging-sdl).

**Comment by bartcubbins** [comment] 2020-09-15 16:14
I just add firmware files one by one as functionality is added.
I'll check the charging. thanks for the feedback;)

**Comment by teodimoff** [comment] 2020-09-15 16:21
Okay thank you for making sony m4 on mainline. If i can help with something, just ping me. :tada:

**Comment by teodimoff** [comment] 2020-09-15 16:24
Sound that this issue is resloved (along with many more things just waiting to be commied). Should i close the issue or leave it open?

**Comment by bartcubbins** [comment] 2020-09-15 16:28
yes, let's close it

**Closed as completed** 2020-09-15 16:29 UTC

**Comment by bartcubbins** [comment] 2020-09-18 00:01
I hope you don't mind if the main branch will be force pushed from time to time

**Comment by bartcubbins** [comment] 2020-09-25 13:48
@teodimoff sorry for taking so long, I just pushed audio support, all you need to get sound is the correct ALSA UCM configuration in the userspace. I'll upload it to a separate repository today or tomorrow. Have fun;)

P.S: Charging issue confirmed and will be fixed soon

**Comment by teodimoff** [comment] 2020-09-26 15:33
@bartcubbins Thanks. No problem. I will test the sound today-tomorrow.  If i see something i will report. Do you want dmesg?

**Comment by bartcubbins** [comment] 2020-09-28 15:31
ALSA UCM 2 configuration: https://github.com/bartcubbins/kanuti_alsa_ucm2

`Do you want dmesg?`
no, thanks;)

**Comment by teodimoff** [comment] 2020-09-28 20:01
Okay i will try the config. I am begining to probe the modem and what it takes to run. I stooped on ofono + qmi. Any pointers will be helpful. I noticed that the wifi somtimes is registred (the device - wlan0) and sometimes it is not. I takes one two restarts on the phone to make a device corectly. Thanks.

**Comment by bartcubbins** [comment] 2020-09-28 20:28
This is a known race condition (wlan).
If you are not as lazy as me, you can open an issue case for each occasion so that I don’t forget or miss anything. There we can also discuss a modem

**Comment by teodimoff** [comment] 2020-10-06 22:03
Cool it looks like it is taking shape. I will try it in a few days. I will see where the modem efford leads.
